---
driver:
  name: docker

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.3
    driver_config:
      privileged: true
      run_command: /usr/sbin/init
#  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[dns-server::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
