# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata
cookbook "dns-server", path: '/home/arubiero/github/Random/cookbooks/dns-server'
cookbook "dhcp", path: '/home/arubiero/github/Random/cookbooks/dhcp'
